a=set()
b=int(input("enter your number 1:\n"))
a.add(b)
b=int(input("enter your number 2:\n"))
a.add(b)
b=int(input("enter your number 3:\n"))
a.add(b)
b=int(input("enter your number 4:\n"))
a.add(b)
b=int(input("enter your number 5:\n"))
a.add(b)
b=int(input("enter your number 6:\n"))
a.add(b)
b=int(input("enter your number 7:\n"))
a.add(b)
b=int(input("enter your number 8:\n"))
a.add(b)
print(a)
