f1=input("Enter your Marks:  ")
f2=input("Enter your Marks:  ")
f3=input("Enter your Marks:  ")
f4=input("Enter your Marks:  ")
f5=input("Enter your Marks:  ")
f6=input("Enter your Marks:  ")
f1=int(f1)
f2=int(f2)
f3=int(f3)
f4=int(f4)
f5=int(f5)
f6=int(f6)
l1=[f1,f2,f3,f4,f5,f6]
print(l1)
l1.sort()
print(l1)